version: '2'
services:
  db:
    image: "postgres:9.6"
    restart: always
    env_file:
     - ./env/pg.env
    volumes:
     - ./data/pgdata:/var/lib/postgresql/data
     - ./docker/pg:/docker-entrypoint-initdb.d/
    ports:
     - "5432:5432"
  elastic:
    image: "nickstenning/elasticsearch-icu"
    volumes:
     - ./data/elastic:/usr/share/elasticsearch/data
    ports:
     - "9200:9200"
     - "9300:9300"
  rabbit:
    image: "rabbitmq:latest"
    ports:
     - "5672:5672"
     - "15672:15672"
  api:
    image: "sensetw-api"
    env_file:
     - ./env/sensemap-backend.env
    volumes:
     - ./src/sensetw/sensemap-backend:/workspace
    ports:
     - "8000:8000"
     - "9230:9229"
  hclient:
    image: "h-client"
    volumes:
     - ./src/client:/workspace
    ports:
     - "8020:8020"
  via:
    image: "via"
    env_file:
     - ./env/via.env
    volumes:
     - ./src/via:/var/lib/via
    ports:
     - "8030:9080"
  h:
    image: "h"
    env_file:
     - ./env/h.env
    volumes:
     - ./src/h:/var/lib/hypothesis
     - /var/lib/hypothesis/node_modules
    ports:
     - "8040:8040"
